---
title: "Plotly in Dashboard"

output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(ggplot2)
library(ggridges)
```

<a href="https://veronical273.github.io/yunjialiu.github.io/index.html" style="padding: 10px 20px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px;">Return to Homepage</a>

```{r}
data(rest_inspec)


rest_inspec_clean = 
  rest_inspec |>
  janitor::clean_names() |>
  select(boro,critical_flag,cuisine_description,inspection_date,inspection_type,score,grade,camis,
         zipcode) |>
  filter(boro == "MANHATTAN",
         cuisine_description %in% c("American","Chinese","Thai","French","Italian","Japanese","Mexican",
            "Indian","Russian","Brazilian","Caribbean",
            "Latin (Cuban, Dominican, Puerto Rican, South & Central American)","Mediterranean",
            "Middle Eastern","Peruvian","Spanish","Jewish/Kosher"),
         score > 0) |>
  mutate(cuisine_description = str_replace(cuisine_description, 
                                           "Latin \\(Cuban, Dominican, Puerto Rican, South & Central American\\)", 
                                           "Latin"))
nyc_latest_inspection =
  rest_inspec_clean |>
  group_by(camis) |> 
  slice_max(inspection_date, with_ties = FALSE) |>
  ungroup()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_latest_inspection |>
  plot_ly(x = ~cuisine_description, y = ~score, type = 'box',color = ~cuisine_description,colors = "viridis") |>
  layout(
    title = "Score Distribution by Cuisine Type in MANHATTAN",
    yaxis = list(title = "Inspection Score"),
    xaxis = list(title = "Cuisine")
    )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_latest_inspection |>
  drop_na(grade) |>
  filter(grade != "Not Yet Graded") |>
  group_by(cuisine_description) |>  
  summarize(
    total_count = n(), 
    grade_a_count = sum(grade == "A", na.rm = TRUE), 
    proportion_a = grade_a_count / total_count
  ) |>
  mutate(cuisine_description = fct_reorder(cuisine_description, proportion_a)) |>
  plot_ly(x = ~cuisine_description, y = ~proportion_a, color = ~cuisine_description, type = "bar", colors = "viridis") |>
    layout(
    title = list(text = "Precentage of A-graded resturants among Different Cuisine in MANHATTAN",
                 font = list(size = 10)),
    yaxis = list(title = "Precentage of A-graded resturants"),
    xaxis = list(title = "Cuisine")
    )
```

### Chart C

```{r}
notcritical_density <- density(nyc_latest_inspection$score[nyc_latest_inspection$critical_flag == "Not Critical"])
critical_density <- density(nyc_latest_inspection$score[nyc_latest_inspection$critical_flag == "Critical"])

# Plot ridge-like density curves by adjusting the y-axis for separation
plot_ly() |>
  add_trace(x = ~notcritical_density$x, y = ~notcritical_density$y, type = 'scatter', mode = 'lines', name = 'Not Critical',fill = "tozeroy") |>
  add_trace(x = ~critical_density$x, y = ~critical_density$y , type = 'scatter', mode = 'lines', name = 'Critical',fill = "tozeroy") |>
  layout(title = "Ridge Plot with Density Curves",
         xaxis = list(title = "Inspection Score", range = c(0, 50)), 
         yaxis = list(title = "", showticklabels = FALSE),  # Hide y-axis labels for simplicity
         legend = list(title = list(text = 'Critical Flag'),
                       orientation = "h",
                       x = 0.5,
                       y = -0.2,
                       xanchor = "center"))
```


